---
title: "Experimenting with shiny"
author: "Mark Ruddy"
date: "27 May 2017"
output: html_document
---


## Sites on a map

First task we'll place sites on a map.


```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(shiny)
library(shinydashboard)
library(leaflet) # Mapping
library(htmltools)
```


Test plot of sites with leaflet widget.

```{r}

sites_grouped <- sites %>%
  select(Locality, Latitude, Longitude) %>%
  distinct(Locality, Latitude, Longitude)
  

map <- leaflet(data = sites_grouped) %>% 
  addProviderTiles("Stamen.TonerLite") %>% 
  addMarkers(lat = ~Latitude, 
             lng = ~Longitude,
             # clusterOptions = markerClusterOptions(),
             popup = ~htmlEscape(Locality))

map
```


Now map in shiny.

```{r}
library(shiny)
library(leaflet)
library(dplyr)

# library(htmltools)

# Data
sites_grouped <- sites %>%
  select(Locality, Latitude, Longitude) %>%
  distinct(Locality, Latitude, Longitude)

# Settings
radius <- 5
weight <- 1
fillOpacity <- 0.6

# ui
ui <- fluidPage(
  sliderInput(inputId = "time",
              label = "Thousands of years Before Present:",
              min = 0, max = 800, value = c(0, 800), step = 2), # 2 values for a range slider
  leafletOutput(outputId = "Map")#), width = "100%", height = "100%")
)

# server
server <- function(input, output) {
  
  # Leaflet map
  output$Map <- renderLeaflet({
    leaflet() %>%
    addProviderTiles("CartoDB.Positron") %>% 
    setView(lng = 12, lat = 52, zoom = 3) %>%
    addCircleMarkers(data = sites_grouped, 
                     lat = ~Latitude, lng = ~Longitude,
                     radius = radius,
                     weight = weight,
                     fillOpacity = fillOpacity,
                     popup = ~as.character(Locality))
  })
  
  # Slider inputs
  observe({
    min_age <- input$time[[1]]
    max_age <- input$time[[2]]
    
    sites_selection <- sites %>% 
      filter(Min_age >= min_age | Max_age >= min_age) %>% 
      filter(Max_age <= max_age | Min_age <= max_age) %>%
      select(Locality, Latitude, Longitude) %>%
      distinct(Locality, Latitude, Longitude)

    leafletProxy("Map") %>% 
      clearMarkers() %>% 
      addCircleMarkers(data = sites_selection,
                       lng = ~Longitude, 
                       lat = ~Latitude,
                       radius = radius,
                       weight = weight,
                       fillOpacity = fillOpacity,
                       popup = ~as.character(Locality)
                       )
    
    
    
   })
  
}

shinyApp(ui = ui, server = server)
```


## Test plotting

### SDQ

Vertical box plot

```{r}
min <- 30
max <- 100

sites_selection <- sites %>%
  filter(Min_age > min | Max_age > min) %>% 
  filter(Max_age < max | Min_age < max) %>%
  select(Locality, Latitude, Longitude) %>%
  distinct(Locality, Latitude, Longitude)

sdq <- sites %>%
  filter(Min_age > min | Max_age > min) %>% 
  filter(Max_age < max | Min_age < max) %>%
  inner_join(y = et, by = c("Assemblage" = "OTU")) %>%
  group_by(ImageID) %>%
  mutate()
  
  
```




